// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ioijnonlacqnjqdhvigl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvaWpub25sYWNxbmpxZGh2aWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MDYzNjksImV4cCI6MjA3ODA4MjM2OX0.5C_hUsThSCCgwotfPVXwVmw_8EoYX9gM9AKU7Dn0IDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);